##Metode Implisit

In [ ]:
import pandas as pd
import numpy as np
import time

def CreateMatrixImplicitParabol(T, q):
    I = T.size
    A = np.zeros((I, I))
    B = np.zeros(I)

    for i in range(1, I-1):
        B[i] += T[i]

        if i == 1:
            B[i] += q*T[i-1]
        else:
            A[i, i-1] = -q

        A[i, i] = 1 + 2*q

        if i+2 == I:
            B[i] += q*T[i+1]
        else:
            A[i, i+1] = -q

    return [A[1:I-1, 1:I-1], B[1:I-1]]


def IterateImplicitParabol(Tj, j, J, q, to):
    A, B = CreateMatrixImplicitParabol(Tj, q)
    X = np.linalg.solve(A, B)

    Tjj = np.concatenate((Tj[0], X, Tj[-1]), axis=None)

    if j < J:
        return IterateImplicitParabol(Tjj, j+1, J, q, to)
    ti=time.time()
    print("Waktu Yang dibutuhkan:", ti-to)
    return Tjj


def ImplicitParabol(env, l, r, I, J, q):
    to = time.time()
    Tj0 = np.concatenate((l, np.full(I, env, dtype="float32"), r), axis=None)

    return IterateImplicitParabol(Tj0, 1, J, q, to)


ImplicitParabol(env=0, l=80, r=20, I=4, J=10, q=0.1)

Waktu Yang dibutuhkan: 0.0005962848663330078


array([80.        , 37.36989882, 14.10277234,  7.0857031 , 10.18847221,
       20.        ])

##Metode Explisit

In [ ]:
import numpy as np
import pandas as pd
import time

def IterateExplicitParabol(Tj, j, I, J, q, to):
    Tjj = Tj.copy()

    for i in range(1, I+1):
        Tjj[i] = Tj[i] + q*(Tj[i-1] - 2*Tj[i] + Tj[i+1])

    if j < J:
        return IterateExplicitParabol(Tjj, j+1, I, J, q, to)
    ti = time.time()
    print("Waktu yang dibutuhkan:", ti-to)
    return Tjj


def ExplicitParabol(env, l, r, I, J, q):
    to = time.time()
    Tj0 = np.concatenate((l, np.full(I, env, dtype="float32"), r), axis=None)
    #ti = time.time()
    #print("Waktu yang dibutuhkan:", ti-to)
    return IterateExplicitParabol(Tj0, 1, I, J, q, to)


ExplicitParabol(env=0, l=80, r=20, I=4, J=10, q=0.1)

Waktu yang dibutuhkan: 0.0010597705841064453


array([80.      , 39.250828, 14.600745,  6.90546 , 10.401878, 20.      ],
      dtype=float32)

##Metode Crank-Nicolson

In [ ]:
import numpy as np
import pandas as pd
import time

def CreateMatrixCrankNicolson(T, q):
    I = T.size
    A = np.zeros((I, I))
    B = np.zeros(I)

    for i in range(1, I-1):
        B[i] += q*T[i-1] + 2*(1-q)*T[i] + q*T[i+1]

        if i == 1:
            B[i] += q*T[i-1]
        else:
            A[i, i-1] = -q

        A[i, i] = 2 + 2*q

        if i+2 == I:
            B[i] += q*T[i+1]
        else:
            A[i, i+1] = -q

    return [A[1:I-1, 1:I-1], B[1:I-1]]


def IterateCrankNicolson(Tj, j, J, q,to):
    A, B = CreateMatrixCrankNicolson(Tj, q)
    X = np.linalg.solve(A, B)

    Tjj = np.concatenate((Tj[0], X, Tj[-1]), axis=None)

    if j < J:
        return IterateCrankNicolson(Tjj, j+1, J, q, to)
    ti = time.time()
    print("Waktu yang dibutuhkan:", ti-to)
    return Tjj


def CrankNicolson(env, l, r, I, J, q):
    to = time.time()
    Tj0 = np.concatenate((l, np.full(I, env, dtype="float32"), r), axis=None)

    return IterateCrankNicolson(Tj0, 1, J, q, to)


CrankNicolson(env=0, l=80, r=20, I=4, J=10, q=0.1)

Waktu yang dibutuhkan: 0.0006704330444335938


array([80.        , 38.31996119, 14.32360929,  6.99685697, 10.30890058,
       20.        ])